### ISSUE TITLE
Many locations are labeled "No Location" in app

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#139]
The reverse geolocation lookup seems buggy. It will display Oakland when I'm at home, but after some scrolling around, it seems to just stall out and read "Undefined Location" eg

![image](https://user-images.githubusercontent.com/15896181/63302743-c9502f80-c292-11e9-971a-9c0fbfabb2b4.png)

**Comment by albullington** [comment]
Dug into this a bit -- I believe this issue is only happening on iOS. It turns out that the [iOS geocoder](https://developer.apple.com/documentation/corelocation/clgeocoder) has a rate limit on geocoding requests, and we're exceeding this rate limit by attempting to update the location name constantly while the user is scrolling around the map. The location picker stalls out on "undefined location" when there have been too many requests in a row (i.e. when the user is scrolling a lot and there are numerous errors in a row). 

Ideally we shouldn't be making any more than 1 geocoding request per minute on iOS. 

@abhasinat I'm wondering if there's a UI solution for this. I noticed the iOS iNaturalist app (which also uses the built-in iOS geocoder) doesn't display location name on the map at all while a user is scrolling around. Is that something we could adopt here?

**Comment by abhasinat** [comment]
There are two primary ways users use the location picker:
1. scanning and moving the pin around on the map
2. typing in a specific location

I'm assuming that this applies only to scenario 1 (correct me if I'm wrong), in which case I would simply not update the map until the user clicks "Search near location," and add UI that indicates that if they are zooming and panning, they need to click "search near location" to send the geocoding request.

**Comment by albullington** [comment]
Yep, only applies to scenario 1.

When you say "not update the map" do you mean not update the location name in the search bar until the user clicks the "search near location" button? The zooming and panning is working fine -- the only thing that is updating too frequently for the iOS geocoder is the location name.

**Comment by albullington** [comment]
Updated iOS so the location name does not update while the user is scrolling around the location picker map. It only updates when a user clicks back to the home screen. 

@abhasinat flagging you as a heads up to test this in the next beta and let me know if there are UI tweaks you'd like to make (such as lighter colored placeholder text in the input field...)

**Comment by abhasinat** [comment]
great to know, thanks for the heads up.
