### ISSUE TITLE
“Species observed” in achievements should link to observations page

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/SeekReactNative#145]
Clicking the species observed on the achievements screen as well as the number beneath it should take the user to the “My observations” page.

![Profile-1-Achievements-ChallengeBadgesUPDATED@2x](https://user-images.githubusercontent.com/44380775/64290829-b341a080-cf1b-11e9-9006-9e3a9f3dd624.png)

**Comment by albullington** [comment]
@abhasinat noting that I added the login button here, but I tweaked the language slightly to "Log in with iNaturalist to post observations to the online community!" Otherwise it sounds to me like syncing obs and posting obs are two different functionalities, and I imagine users might expect to be able to sync all of their observations.

**Comment by abhasinat** [comment]
Sounds great, good call.

**Comment by albullington** [comment]
@abhasinat one other thing to note is that I added a "sign out of iNaturalist" state with the same text as the one on the iNat Stats screen -- something you might want to test in the beta release.

**Comment by abhasinat** [comment]
Solid!
