### ISSUE TITLE
Prompt "leave a review" modal in iOS

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/SeekReactNative#156]
We want to add an option to prompt users to leave a review in Seek. Apple allows this natively, and limits this modal to appearing 3 times per year. Details here: [https://developer.apple.com/app-store/ratings-and-reviews/](url)

This modal should appear after the user clicks "Continue" on the "You leveled up!" modal at 30 species (Surveyor) and 75 species (Biologist).

Here is the flow:
- user observes their 30th/75th species and gets to the species ID success screen
- user clicks any button to make the "You Leveled Up!" modal appear
- user clicks "Continue", and the native Apple "Enjoying Seek?" modal appears

Notes:
- If the user has already left a review on the App Store for Seek at any time, this modal should not appear
- are children allowed to leave reviews? if not, should this be for logged-in users only? I tried researching this, but couldn't find much. My gut says show this modal to everyone.

**Comment by albullington** [comment]
Implemented this, with the caveat that it won't show up on TestFlight, so we'll only be able to confirm that it's working once it's in production (it looks good in development mode).

Functionality is pretty limited -- we don't have a way to check which users have left App Store reviews, and we can't even tell if a user clicks on the review modal. I'm showing this to everyone for now, because it doesn't appear to take users out of the app when they submit.
