### ISSUE TITLE
Add flash to AR Camera

### ISSUE THREAD

**Issue by abhasinat** [inaturalist/SeekReactNative#158]
On the AR camera, we want to add an option to turn on the camera flash while the user is using the camera. I have two options, with option 1 being the preferred route.

1. My ideal scenario is to have a button that can be clicked on and off, so that the flash can remain on while the user is using the AR Camera to scan, and not just when they take a photo. That would make the Camera easier to use in low light, and would also make it easier to focus on organisms with the flash constantly on. This would mean there are two states that the user can toggle by pressing the flash button, which would turn the camera flashlight on and off:
- flash OFF (default state): flashlight is off while the AR camera is open
- flash ON: flashlight is on while the AR camera is open

2. If that's not feasible, the flash could function similarly to how most camera phones do flash: only going off when the shutter button is pressed to take a picture. This would mean three states that the user can toggle between. These states can be changed at any time, and only affect the behavior of the flash after the camera button is pressed:
- flash AUTO (default state): when shutter button is pressed, flash will go off depending on how light/dark it is
- flash ON: when shutter button is pressed, flash will go off
- flash OFF: when shutter button is pressed, flash will not go off

I've added states for all of these on Zeplin:
- [flash ON](https://zpl.io/aneWe3O)
- [flash OFF](https://zpl.io/aBZYZzq)
- [flash AUTO](https://zpl.io/bAnYnRe)

The flash icons I'm using are from the [react native vector icons](https://oblador.github.io/react-native-vector-icons/):
- flash ON/AUTO: "ios-flash"
- flash OFF: "ios-flash-off"

**Comment by albullington** [comment]
Hey @abhasinat, could you open an issue in the [react-native-inat-camera ](https://github.com/inaturalist/react-native-inat-camera/issues) library? This will need to be implemented natively before I can do anything to update the UI.

I also wouldn't recommend using the [react-native-vector icons](https://oblador.github.io/react-native-vector-icons/) library in this situation since we haven't used it for anything else in the app. Libraries add a decent amount of bulk, so we would be making the app significantly larger in size without gaining much new functionality. Better to stay consistent and use our own icons.

**Comment by abhasinat** [comment]
Sure, I'll make some custom icons for this. Should I just paste this entire issue into react-native-inat-camera or does anything need to be changed?

**Comment by albullington** [comment]
Pasting should be fine.

**Comment by albullington** [comment]
I'm closing this for now since it's dependent on implementation in the react-native-inat-camera library.
