### ISSUE TITLE
rotate text overlayed by ARCamera when phone orientation is landscape

### ISSUE THREAD

**Issue by joergmlpts** [inaturalist/SeekReactNative#223]
When I take look at lifeforms in landscape orientation, the overlayed text looks like this:

![rotate](https://user-images.githubusercontent.com/66563749/83973560-1c37b980-a89c-11ea-86e4-71cf5743ca00.jpg)

The overlayed text could be more readable if it were rotated and always horizontal. In the field, in the sun or when wearing sunglasses, the text is not always easy to read.

**Comment by albullington** [comment]
Thanks for your feedback. However, leaving the text in portrait mode is an intentional UI choice. The AR Camera is designed to only give users reliable predictions in portrait mode. By creating the entire UI of Seek in portrait mode, we aim to discourage users from using their phone in landscape where they will likely be confused and frustrated by the predictions they receive.
