### ISSUE TITLE
Update inactive taxon ids before posting to iNat

### ISSUE THREAD

**Issue by albullington** [inaturalist/SeekReactNative#369]
**Is your feature request related to a problem? Please describe.**
As soon as the training process for a model starts, the list of taxa we use in the AR Camera may already be out-of-date. Since we don't currently map inactive taxa with current ones in Seek, this leads to some observations being posted to iNat with an inactive taxon id (like this [example](https://forum.inaturalist.org/t/inactive-taxon-suggested-by-computer-vision/15370/5)).

**Describe the solution you'd like**
Observations posted to iNaturalist should have the most up-to-date taxa IDs. To achieve this, we'll need to add a step in the posting to iNat process to resolve taxon mapping issues. There are three possible scenarios:

1. The taxon is no longer active and has no current version, so a user can’t use it (or can only use it with a warning)
2. The taxon has been replaced by one taxon, so Seek will automatically update it for the user before posting
3. The taxon has been replaced by two taxa, so a user must actively choose the one they want before submitting

This will need design (@abhasinat), and we'll need to consider whether this should happen while the user is on the posting to iNat screen (when the user is not guaranteed internet or the ability to fetch this data from the API) or when bulk uploads are happening (when internet must be available for a successful upload, but a user can't see any details about which observation is uploading -- we might need a modal to provide more context here).

**Describe alternatives you've considered**
@pleary suggested a few alternatives: 

1. An API endpoint that Seek could call to ask for all taxon changes (which would require the API to know about all versions of the model that Seek could be running)
2. A flag on observation create where we automatically try to map to the latest taxon (which wouldn't always work when a taxon has split into multiple taxa)
3. We could generate a model mapping on a regular schedule (say, every two weeks) and ship this in new versions of Seek (which wouldn't help if users aren't updating to the latest app version)

**Additional context**
Implementation: Use the `is_active` property of the taxon details API to check for inactive taxa and the `current_synonymous_taxon_ids` property to return any updated, active taxa IDs. Depending on how we display this in Seek, we might also need a second API call to fetch the new taxon scientific name(s) and common name(s).

**Comment by abhasinat** [comment]
My approach would be to not create any new designs for this and handle this all in the bulk uploader. I believe Seek users aren't too concerned about taxon changes, otherwise they'd use iNat, and the ones who use iNat will be able to figure out why this happened. So I don't think Seek users need to know what's happening here in these niche cases. Here are my ideas:

1. If the taxon is no longer active, I would roll up the taxonomy to the first active taxon. i.e. assume Dark-eyed Junco [_Junco hyemalis_] is no longer active, so when uploaded to iNat, the ID associated with the observation goes up to genus _Junco,_ the first rank that is active.
2. If the taxon has been replaced by one taxon, I would have Seek automatically update the ID to the new taxon before posting to iNat.
3. If the taxon has been replaced by two taxa, I would roll up the taxonomy to the first active common ancestor of those two taxa, and associate the observation with that common ancestor ID on iNat.

**Comment by jwidness** [comment]
That's what I'm getting too.  I'll close out the flag on the taxon since we can't really force people to update their app.
