### ISSUE TITLE
Bee Challenge (May 2022) - Won't load species seen nearby

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#472]
**Describe the bug**
When tapping on "Tap to load species nearby", I see "We found no species nearby in this challenge..." even though I've observed no bees in Seek and there are plenty nearby in the Bay Area.

**To Reproduce**
1. Start the Bee Challenge
2. Scroll down and tap on "Tap to load species nearby".
3. Spinner shows briefly, then you see "Tap to load species nearby" again.
4. Tap on it again.
5. See spinner, then see "We found no species nearby in this challenge..."

**Expected behavior**
I should see bee species seen nearby. Other challenges seem to work fine.

**Screenshots**
Screen recording here: https://inaturalist.slack.com/archives/C9KMT4MK2/p1660939359243709

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOS 15.6.1
 - Version 2.14.2 (252)

**Additional context**
Both cell and wifi were on, I'm using wifi.

**Comment by kueda** [comment]
Johannes and I determined that the problem is that bees (Epifamily Anthophila) are on the [list of dangerous animals](https://www.inaturalist.org/lists/945029) Seek doesn't allow people to view nearby observations of. So the solution should be to remove bees from that list, assuming everyone is ok with that (which they seem to be). So that's what I'll do. We can only verify that it worked after the Redis cache expires (in 1 hour?).

**Comment by jtklein** [comment]
Can confirm that removing bees (Epifamily Anthophila) from the list of dangerous animals has resolved this issue.
