### ISSUE TITLE
Camera crashes app on iPod Touch

### ISSUE THREAD

**Issue by tiwane** [inaturalist/SeekReactNative#49]
A user reports that, on their son's iPod Touch running iOS 9.3.5, "every time we try to access the camera the app exits/crashes."

**Comment by albullington** [comment]
@tiwane I can't seem to get iOS 9.3 to advance past the splash screen, so I'm going to say we probably won't support that anytime soon since I don't have a way to test it.

However, I was able to run Seek on iOS 10 and realized the error messages weren't showing up in the camera, so I've added the error text back in. Not sure if that will help with the crashes, but ideally it will give some context to folks running devices older than iOS 11.

**Comment by albullington** [comment]
@tiwane and @abhasinat I'm closing this since we decided to change the deployment target on iOS to 10 and above. 

Is there anything we need to do (blog post, forum post) etc. to announce to users that we're dropping support for iOS 9?

**Comment by tiwane** [comment]
No, I don't think that's necessary.
