### ISSUE TITLE
No exit from Post to iNat flow

### ISSUE THREAD

**Issue by kueda** [inaturalist/SeekReactNative#78]
Sartratic? Sartre-esque? How has Sartre not be adjectivized? Anyway, when I go through the post to iNat flow in Android build 28, I end on a "Posted to iNat" screen with an "OK" button. Tapping OK just brings me back to the post to iNat form... where I can either post the same observation again or back out all the way through the photo-adding flow. Seems to me that "OK" button should bring me back tot he home screen. Maybe it should also be impossible to post the same photo to iNat twice.

**Comment by albullington** [comment]
I changed this last week to send users back to the results screen, rather than the home screen. @abhasinat you still think sending users to results is the best user experience, right?

**Comment by abhasinat** [comment]
Yes, I think once a user has successfully posted to iNat, having the "OK" button take them back to the results screen is the best UX– it's where they entered the posting flow, so that's where they'd expect to end imo.

When a post fails to upload, however, I think the user should be taken back to the iNat form to try submitting it again. This is something we can implement post v2.1.0, and I think it's fine for both states to take the user back to the results screen for now.

**Comment by albullington** [comment]
Rad. I'm closing this, since the latest version on TestFlight already takes them to results screen on success and back to the iNat form on failure.
