### ISSUE TITLE
Bug in Taxonomy Display on Seek

### ISSUE THREAD

**Issue by bobby23-3** [inaturalist/SeekReactNative#98]
In the version of Seek currently available, a taxon rank is not displayed under a species' profile if the rank lacks a common name. For popular taxa this issue does not occur because many of the ranks have a common name, like in this Woodchuck example:
![woodchuck](https://user-images.githubusercontent.com/51837167/59537899-03353c00-8ec6-11e9-9b46-10ab4d6600f5.jpg)

However, this becomes a problem with plants and invertebrates, where a lot of ranks don't have common names. For the European Harvestman, for example, both its Family and Genus are unlisted.
![harvestman](https://user-images.githubusercontent.com/51837167/59537937-252ebe80-8ec6-11e9-8b96-b1b146619aff.jpg)

On iNaturalist.org, the full taxonomy for this species would still be displayed even though they lack common names:
![harvestman-inat](https://user-images.githubusercontent.com/51837167/59537941-2cee6300-8ec6-11e9-993d-63d9539d74a1.png)

I imagine this may look a little more jarring in non-English versions of Seek, since the non-English common names for many taxa are missing from iNaturalist, even for popular groups like mammals.

**Comment by albullington** [comment]
@abhasinat I believe I originally added the check for common name to keep the design looking consistent, since it would look odd to have some taxons with two lines and some with one line. Do you think we should update this to use the scientific name when there's no common name available? It would look like this:
 
![taxonomy](https://user-images.githubusercontent.com/35536439/59645444-a5ebf580-9126-11e9-9343-e0a08b4763d6.png)

**Comment by abhasinat** [comment]
Thanks @bobby23-3! I think showing scientific name instead of common name here is totally fine. I like the implementation you've shown here @albullington.
